<head>
	<style type="text/css">
		#footer{position: relative; height: 50px;	margin:0px auto; background-color:#2c3747;}
		.footer_elements{position: relative; color:#fff; display: table;}
		#fb{top:10px; margin-left:15px; margin-right:auto;}
		#fb a{text-decoration:none; color: #fff;}
		#copywright{margin-left:auto; margin-right:15px; top:-5px;}

	</style>
</head>

<div id='footer'>
	<div id='fb' class='footer_elements'><a href='https://www.facebook.com/'>Share The Link On facebook</a></div>
	<div id='copywright' class='footer_elements'>&copy; IT Association</div>

</div>