<head>
	<style type="text/css">
		#header{position: relative; height: 75px; background-color:#2c3747;}
		.header_elements{position: relative;}
		.logo{height: 70px;	width:70px;}
		#it_logo{background:url('../imgs/logo/it_logo.png') no-repeat center center / 100% 100% transparent;	top:3px; margin-left:15px; margin-right:auto;}
		#title_text{background:url('../imgs/logo/forum_text.png') no-repeat center center / 100% 100% transparent;	top:-68px; margin: 0px auto; 	height: 70px; width: 400px;}
		#forum_logo{background:url('../imgs/logo/forum_logo.png') no-repeat center center / 100% 100% transparent;		top:-138px; margin-left: auto; margin-right:15px;}
	</style>
</head>

<div id='header'>	
		<div id='it_logo' class='logo header_elements'></div>
		<div id='title_text' class='header_elements'></div>
		<div id='forum_logo' class='header_elements logo'></div>
</div>